# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

[versions]
agp = "8.13.2"
kotlin = "2.0.21"

# Select the desired versions of Horizon OS JSDK and Support Library
horizon-os-jsdk = "204"
horizon-os-support-library = "0.1.0"

# Declare libraries for Horizon OS JSDK and Support Library for use as dependencies in build.gradle.kts
[libraries]
horizonos-jsdk = { group = "com.meta.horizonos", name = "horizon-os-jsdk", version.ref = "horizon-os-jsdk" }
horizonosx-core = { group = "com.meta.horizonosx", name = "core", version.ref = "horizon-os-support-library" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
